<?php
/**
 * Created by PhpStorm.
 * User: paulv
 * Date: 2017/10/29
 * Time: 22:27
 */

namespace frontend\controllers;


use yii\web\Controller;

class DefaultController extends Controller
{
    public  $result;

    public  function  beforeAction($action)
    {


        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}